Demo/Demo/Controllers/MailFolderController.cs
using Demo.Helpers;
using Demo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Demo.Controllers
{
    
    public class MailFolderController : BaseController
    {
        [Authorize]
        // GET: MailFolder
        public async Task<ActionResult> Index()
        {
            var mailFolder = await GraphHelper.GetMailFoldersAsync();
           
            return View(mailFolder);
        }
        public async Task<ActionResult> List_Messege()
        {
            var list_mess = await GraphHelper.GetMessage();
            return View(list_mess);
        }

        public ActionResult Create_Message()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> CreateMessage(Messeges ms)
        {
            await GraphHelper.Create_Messege(ms);
            return  RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<ActionResult> Send_Message(string id)
        {
             GraphHelper.Send_Message(id);
            return RedirectToAction("List_Messege");
        }
        public ActionResult Send_Mail()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> SendMail(Messeges ms)
        {
            GraphHelper.Send_Mail(ms);
            return RedirectToAction("Index");
        }
    }
}

Demo/Demo/Views/MailFolder/Create_Message.cshtml
@model Microsoft.Graph.Message
@{
    ViewBag.Title = "Create_Message";
}

<h2>Create_Message</h2>
@using (Html.BeginForm("CreateMessage", "MailFolder", FormMethod.Post))
{

    <div class="row" style="margin:10px">
        <p>Subject</p>
        <input type="text" name="Subject" />
    </div>
    <div class="row" style="margin:10px">
        <p>Content</p>
        <input type="text" name="body.Content" />
    </div>
    <div class="row" style="margin:10px">
        <p>Email</p>
        <input type="text" name="emailAddress.Addressto" />
    </div>    
    <div class="row" style="margin:10px">

        <input type="submit" value="Submit" />
    </div>
}

Demo/Demo/Views/MailFolder/Index.cshtml
@model IEnumerable<Microsoft.Graph.MailFolder>

@{
    ViewBag.Title = "Index";
}

<div>@Html.ActionLink("Create Message", "Create_Message")</div>
<div>@Html.ActionLink("Send Mail", "Send_Mail")</div>
<h1>MailFolder</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Display Name</th>
            <th scope="col">childFolderCount</th>
            <th scope="col">unreadItemCount</th>
            <th scope="col">totalItemCount</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.DisplayName</td>
                <td>@item.ChildFolderCount</td>
                <td>@item.UnreadItemCount</td>
                <td>@item.TotalItemCount</td>
                
            </tr>
        }
    </tbody>
</table>

Demo/Demo/Views/MailFolder/List_Messege.cshtml
@model IEnumerable<Microsoft.Graph.Message>

@{
    ViewBag.Title = "List_Messege";
}

<div>@Html.ActionLink("Create Message", "Create_Message")</div>
<h1>List Message</h1>
<table class="table">
    <thead>
        <tr>         
            <th scope="col">Subject</th>   

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            using (Html.BeginForm("Send_Message", "MailFolder", new { @id = item.Id }))
            {
            <tr>              
                <td>@item.Subject</td>              
                
                <td><input type="submit" value="send"/></td>
                
            </tr>
                }
            }
    </tbody>
</table>

Demo/Demo/Views/MailFolder/Send_Mail.cshtml
@{
    ViewBag.Title = "Send_Mail";
}

<h2>Send_Mail</h2>
@using (Html.BeginForm("SendMail", "MailFolder", FormMethod.Post))
{

    <div class="row" style="margin:10px">
        <p>Subject</p>
        <input type="text" name="Subject" />
    </div>
    <div class="row" style="margin:10px">
        <p>Content</p>
        <input type="text" name="Body.Content" />
    </div>
    <div class="row" style="margin:10px">
        <p>Email</p>
        <input type="text" name="EmailAddress.Addressto" />
    </div> 
    <div class="row" style="margin:10px">
        <p>Email</p>
        <input type="text" name="EmailAddress.Addresscc" />
    </div>
    <div class="row" style="margin:10px">

        <input type="submit" value="Submit" />
    </div>
}