Demo/Demo/Controllers/CalendarController.cs
using Demo.Helpers;
using Demo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Demo.Controllers
{
    public class CalendarController : BaseController
    {
        // GET: Calendar
        [Authorize]
        public async Task<ActionResult> Index()
        {
            var events = await GraphHelper.GetEventsAsync();

            // Change start and end dates from UTC to local time
            foreach (var ev in events)
            {
                ev.Start.DateTime = DateTime.Parse(ev.Start.DateTime).ToLocalTime().ToString();
                ev.Start.TimeZone = TimeZoneInfo.Local.Id;
                ev.End.DateTime = DateTime.Parse(ev.End.DateTime).ToLocalTime().ToString();
                ev.End.TimeZone = TimeZoneInfo.Local.Id;
            }

            return View(events);
        }
        
        public ActionResult Create_calendar()
        {          
            return View();
        }  
        [HttpPost]
        public async Task<ActionResult> Createcalendar(CalendarEvent events)
        {
            await GraphHelper.CreateEvent(events);
            return RedirectToAction("Index");
       
        }
        [HttpPost,ActionName("Delete")]
        public async Task<ActionResult> Delete_event(string id)
        {
            GraphHelper.Del_event(id);
            return RedirectToAction("Index");
        }
    }
}

Demo/Demo/Views/Calendar/Create_calendar.cshtml
@{
    ViewBag.Title = "Create_calendar";
}

<h2>Create_calendar</h2>
@using (Html.BeginForm("Createcalendar", "Calendar"))
{
 
    <div class="row" style="margin:10px">
        <p>Subject</p>
        <input type="text" name="Subject" />
    </div>
    <div class="row" style="margin:10px">
        <p>Content</p>
        <input type="text" name="body.Content" />
    </div>
    <div class="row" style="margin:10px">
        <p>Start</p>
        <input type="text" name="Start.DateTime" />
    </div>
    <div class="row" style="margin:10px">
        <p>End</p>
        <input type="text" name="End.DateTime" />
    </div>
    <div class="row" style="margin:10px">

        <input type="submit" value="Submit" />
    </div>


}

Demo/Demo/Views/Calendar/Index.cshtml
@model IEnumerable<Microsoft.Graph.Event>

@{
    ViewBag.Current = "Calendar";
}

<h1>Calendar</h1>
<div>@Html.ActionLink("Create", "Create_calendar")</div>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Organizer</th>
            <th scope="col">Subject</th>
            <th scope="col">Start</th>
            <th scope="col">End</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            using (Html.BeginForm("Delete", "Calendar", new { @id = item.Id}))
            {
            <tr>             
                <td>@item.Organizer.EmailAddress.Name</td>
                <td>@item.Subject</td>
                <td>@Convert.ToDateTime(item.Start.DateTime).ToString("M/d/yy h:mm tt")</td>
                <td>@Convert.ToDateTime(item.End.DateTime).ToString("M/d/yy h:mm tt")</td>
                <td><input type="submit" value="xoa" /></td>
            </tr>
            }
        }
    </tbody>
</table>